### ISSUE TITLE
Troubles with netCDF4

### ISSUE THREAD

**Issue by sebmeng** [Deltares/imod-python#1227]
Hello Community!
I'm a new user, I installed imod in a new environment with mamba (as suggested in the docs)

```
mamba create -n imodenv
mamba install -n imodenv imod --channel conda-forge 
```

But when I try to run this basic script in VS code:

```

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.ndimage
import xarray as xr

import imod

gwf_model = imod.mf6.GroundwaterFlowModel()

layermodel = imod.data.hondsrug_layermodel()

# Make sure that the idomain is provided as integers
idomain = layermodel["idomain"].astype(int)

# We only need to provide the data for the top as a 2D array. Modflow 6 will
# compare the top against the uppermost active bottom cell.
top = layermodel["top"].max(dim="layer")

bot = layermodel["bottom"]

top.plot.imshow()
```

I get this error in layermodel = imod.data.hondsrug_layermodel():

"
...
ImportError: DLL load failed while importing _netCDF4: The specified procedure could not be found."
"

I tried reinstalling netCDF4 with mamba but it didn't work :( , maybe soneone can help me to see what I am missing?

Thanks in advance!

Sebastian

**Comment by JoerivanEngelen** [comment]
Hi Sebastian, 

Sorry to hear you are facing installation issues! 

I just saw NetCDF4 had an update, which might be the cause. 
Could you run ``mamba list netcdf4`` and share the information it prints?
And to be sure, run ``mamba list xarray`` as well?

Cheers,
Joeri

**Comment by JoerivanEngelen** [comment]
Note to myself and the rest of the dev team: this might be a reason to prioritize https://github.com/Deltares/imod-python/issues/1185 more

**Comment by sebmeng** [comment]
Thanks for your reply Joeri!

for netCD4:
```

(imodenv) C:\Users\926741>mamba list netcdf4
# packages in environment at C:\Users\926741\AppData\Local\anaconda3\envs\imodenv:
#
# Name                    Version                   Build  Channel
netcdf4                   1.7.1           nompi_py312h39e0dc6_102    conda-forge
```

For xarray:
```

(imodenv) C:\Users\926741>mamba list xarray
# packages in environment at C:\Users\926741\AppData\Local\anaconda3\envs\imodenv:
#
# Name                    Version                   Build  Channel
xarray                    2024.9.0           pyhd8ed1ab_0    conda-forge
```

Best,
Sebastian

**Comment by JoerivanEngelen** [comment]
Hmmm, those appear to be the versions on my machine as well, where everything works.
We work with pixi a lot and recommend installing in this manner (we still have to update the documentation)

To get exactly my python environment, you can do the following:

1. install [pixi ](https://pixi.sh/latest/)
I see you work on Windows, so open Powershell, and run:

```powershell
iwr -useb https://pixi.sh/install.ps1 | iex
```

2. Copy the ``pixi.toml`` and ``pixi.lock`` file in this repository to the folder you want to work in.
3. ``cd`` to the folder you want to work in your terminal
4. run ``pixi shell -e interactive``; this will start a shell session in a isolated pixi python environment
5. run ``python <name of your script>``

If the error then still persists, this is probably caused by a dependency clash somewhere: You might have another existing NetCDF4 installation somewhere installed globally in your PATH variable that is clashing. Are there any other Python installations on your machine, outside of your Anaconda installation?

If you keep on being stuck, you might be able to use this script to check what DLL's are imported, and see if anything weird is listed in that:

**list_dll.py**

```python
# e.g. finding the shared libs (dll/so) our python process loaded so far ...
import os

import psutil

import imod

p = psutil.Process( os.getpid() )
for dll in p.memory_maps():
  print(dll.path)
```

Then run:

```powershell
pixi shell -e interactive
python list_dll.py > log.txt 
```

And see if anything weird is printed in that logfile.

**Comment by sebmeng** [comment]
I still have issues :( 
Just removed the environment, created it again and run it through anaconda prompt (not VS code) and still get the same error.
These are my environment variables:

![image](https://github.com/user-attachments/assets/1652d32b-9abb-4203-b8bb-cfa93b1bd55b)

Could be because I have VS code in my system variables? I use it for coding (and jupyter notebooks as well)

**Comment by sebmeng** [comment]
I did another test. I downloaded Deltaforge and opened VS code though the deltaforge prompt for it to recognize the deltaforge base kernel. But I still have the same problem with the netCDF4 dll :( 
I don't know what to do really. The IMOD experience hasn't been smooth at all as I thought.
Do you have any suggestions? 

Best,
Sebastian
