### ISSUE TITLE
Improve TWRI Regridding example

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#596]
In GitLab by @JoerivanEngelen on Oct 19, 2023, 11:18

There are some flaws/mistakes in the TWRI Regridding example which we can improve:

- The regridded plots don't seem to differ much in terms of cell size. We are going from 5000 to 3751.0/1670.0 and apparently this makes for only a subtle decrease visually.
- Furthermore the `dx` `dy` in the title of the plot stay 5000 (perhaps a fix for the Regridder?), making for a very confusing plot (I first thought the example was bugged).
- "TWRI Regridding" is not a very descriptive name, we'd better name it something like: "Differens ways to regrid models"
- The bullet list in the introduction doesn't work unfortunately (sphinx' .rst is very picky about newlines, so probably the result of that).
- post (or fix) issue on xugrid for updating dx/dy on regridding

**Comment by luitjansl** [comment]
"Furthermore the dx dy in the title of the plot stay 5000 (perhaps a fix for the Regridder?), making for a very confusing plot (I first thought the example was bugged)."

The issue here was that for some arrays the regridder is not called. For example a K-array with only a layer dimension. Such arrays carry the dx-dy  coordinates. Adding them to the dataset will update the dx/dy coordinates of the dataset. This can be fixed by removing dx/dy from layer -based arrays when regridding.
