### ISSUE TITLE
For RIV, DRN and GHB packages it should be possible to automatically assign them to the appropriate layers of the model.

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#628]
In GitLab by @HendrikKok on Nov 7, 2023, 10:41

This is especially relevant for MF6 models, since there are strict input checks. 

Possible logic would be:
1.	Assign to top active layer (for DRN and GHB for example)
2.	Assign to one layer based on bottom- or stage level
3.	Assign to all layers where stage or bottom > cell-bottom. Conductance should be distributed based on:

        a.	Intersection length
        b.	Transmissivity contributions
        C.      ...

Requirements:

* Create some place to store settings for each package.
* The user should be able to alter these settings, provide custom settings
* Create functions to find layer based on provided z value (could be bed level, could be elevation), option 2, and and a function which returns all active cells above a provided z value, option 3.
* For option 1, we can use the methods already added to imod.prepare.layer

Tasks

- [x] #949
- [x] #950
- [x] #974
- [x] #975
- [x] #951

**Comment by JoerivanEngelen** [comment]
See this report from Sweco describing different methods to allocate cells with depth and distribute conductances over depth in iMOD5. Nice summary of requirements for this story!

[20240129 Conductanceverdeling iMOD5.docx](https://github.com/Deltares/imod-python/files/14222631/20240129.Conductanceverdeling.iMOD5.docx)

I translated the list of settings in iMOD5.6 briefly below. We could create a set of utility functions to support this, so that users can mix and match what they'd like.

Allocation RIV cells with depth:

* Laying inbetween river stage and bottom elevation (IDEFFLAYER=0)
* First active cell to bottom elevation (IDEFFLAYER=-1)
* First active cell to bottom elevation, cells above river stage can only drain  (IDEFFLAYER=1)
* In cells where bottom elevation is located  (IDEFFLAYER=2)

Distribution conductance with depth:

* "default" iMOD5 option whatever that means?
* equally over layers
* weighted by layer thicknesses
* weighted by protruded layer thicknesses
* weighted by layer transmissivity
* weighted by horizontal hydraulic conductivity
