### ISSUE TITLE
The SpecificStorage class returns the wrong error message for a mismatch in dims

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#674]
In GitLab by @HendrikKok on Nov 30, 2023, 16:04

For the variable ‘convertible’, the error message is ‘float64 != np.int’ is raised, while:

1-	dtype of array is np.int32,
2-	the given array had shape of (nlayer – 1).

Probably the correct error on the array shape, returns the wrong error message.

**Comment by Manangka** [comment]
In GitLab by @HendrikKok on Dec 5, 2023, 11:03

Hi Joeri,

I tested it on a large model (as always). The quickest way to reproduce this, is to use the existing tests for the sto-package I think. For the convertible argument use a 3d xarray with the correct dtype, but with a layer dimension of size layer -1. This should result in this error.

**Comment by Manangka** [comment]
In GitLab by @HendrikKok on Dec 5, 2023, 13:47

at voila @ test-error-message-sto-package-mf6

**Comment by JoerivanEngelen** [comment]
Thanks! I checked the branch and I think this stems of a wider inconvenience: The DataArrays provided to a Package are immediately set as variable in a dataset upon Package initialization. Then a similar thing happens as calling:

```
xr.merge([{"specific_yield": sy_layered, "transient": transient, "convertible": convertible_missing_layer}], join="outer")
```

This will replace the missing indexes in ``convertible_missing_layer`` with ``np.nan``, which causes the integer array to be converted to float. In that sense the validation is doing what it is supposed to do: It detects a coordinate with the wrong type in your dataset.

We could make this more explicit, because iMOD Python expects coordinates to match exactly. We could therefore take an alternative approach to initiating the dataset and use something like:

```
xr.merge([{"specific_yield": sy_layered, "transient": transient, "convertible": convertible_missing_layer}], join="exact")
```

This throws the error:

```
ValueError: cannot align objects with join='exact' where index/labels/sizes are not equal along these coordinates (dimensions): 'layer' ('layer',)
```

Which already points the user better to the culprit.

An alternative would be to implement validation schemes which should be called upon initialization BEFORE the dataset is created. This has the benefit that we could provide more info to the user, but the disadvantage that we are creating duplicate logic. So far the strategy of iMOD Python has been to leverage ``xarray`` where possible and extend where needed.

**Comment by JoerivanEngelen** [comment]
Closing this for now (the culprit has been found), progress on resolving this issue can be followed here: https://github.com/Deltares/imod-python/issues/708
