### ISSUE TITLE
investigate if we can test for changes in the public api

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#782]
We would like to protect our public api from unintentional changes

We would like a test that fails if:
-a public api method is removed or renamed
-the signature of a public api function changes (at least the mandatory arguments, or their order, or their type)'
-the return value type of a public api function

Note: Not all public methods need to be protected in this way- only the ones we mark as being public api. 

Is there a python package that can help with this? or with some of this?

**Comment by Huite** [comment]
How would this work without massive duplication? -- You'd have to store "contracts" for each method somewhere else.
Doing it automatically cannot work either because no change would ever be allowed. At the most, you could set something up to give a warning, not a failure.

The primary issue, I think, is that it's not directly clear what is public. This is a common problem. Xarray "solves" it by defining it through the documentation, and so do many other packages.
https://docs.xarray.dev/en/stable/getting-started-guide/faq.html#what-parts-of-xarray-are-considered-public-api

I've always used these rules:

1. Everything with an underscore is always private and may be subject to arbitrary changes.
2. Modules and classes that are not in the API reference are never public, whether they have underscores or not.
3. Anything on public classes (so it's in the API reference) is public if it doesn't have an underscore. This rule technically conflicts with rule 2, but it's possible something was accidentally not added to the API ref (should then obviously be fixed). But it's possible a user has found out by tab completion (which won't happen with underscores prefixes).

**Comment by JoerivanEngelen** [comment]
@Huite comment is clear, thanks! Closing for now.

**Comment by Manangka** [comment]
You could work with an internal class to hide the private methods. This is done in c++ and resambles the PIMP idiom.
But i don;t know if it is worth the effort

```
class PublicCLass:
    
    class InternalClass:
        def __init__(self, **kwargs):
            # initialize dataset
        
        def public_method1(self)

        def public_method2(self)
            
        def private_method3(self):
    def __init__(self, **kwargs):
        self.data = InternalClass(kwargs)
        
    def public_method1(self):
        self.data.internal_method1()
    def public_method2(self):
        self.data.internal_method2()
```
