### ISSUE TITLE
use partitioning on real-world model

### ISSUE THREAD

**Issue by luitjansl** [Deltares/imod-python#841]
The partitioning of flow and transport simulations has been tested on simple models, but we would like to try it on a more complex, real-world simulation. For that we can use Teun's model, which can be found here: n:\Deltabox\Postbox\Engelen,van Joeri\test_mf6\

**Comment by JoerivanEngelen** [comment]
Update
--------

Splitting the model worked succesfully, after fixing two validation mistakes. However, comparing heads shows differences when the buoyancy package is active. I haven't found the precise cause of this out.

The following plots show the differences: 

```python
(head["head"] - head_split["head"]).isel(time=ind[0], layer=10)
```

With buoyancy:

![image](https://github.com/Deltares/imod-python/assets/9744750/f7004e3f-f317-4718-b0bd-ac4351c7d54b)

Without buoyancy:

![image](https://github.com/Deltares/imod-python/assets/9744750/7c2695ae-e3fa-4293-a221-7f451ad8d2bc)

With buoyancy, but density slope = 0.0, 
so that density has no effects on heads but the picard iteration scheme is active:

![image](https://github.com/Deltares/imod-python/assets/9744750/f2f6498e-407c-443e-985e-d42cb9310000)

Things I have tried that had no effect before looking at density:

* In the exchange file, change IHC=1 to IHC=2. This even worsened errors with a factor 4.
* Remove vertical staggering of grid, by setting all top and bottoms to one single value (instead of differing over x,y). No effect.
* Set the solver settings of both the transport as well as flow solver stricter (reducing DVCLOSE by a factor 10). No effect.
* Remove advection package. No effect.
