### ISSUE TITLE
empty top en bottom of the legend plot

### ISSUE THREAD

**Issue by JaccoHoogewoud** [Deltares/imod-python#856]
Hi,

when i use imod visualize (sometimes?) the legend is not complete.

i used the colors and breaks:
```
def set_difcolors():
    colors_diff = [ (80/255 ,0      ,0      ),
                    (140/255,0      ,0      ),
                    (255/255,102/255,0      ),
                    (255/255,204/255,0      ),
                    (255/255,234/255,111/255),
                    (255/255,255/255,185/255),
                    (227/255,227/255,192/255),
                    (200/255,200/255,200/255),
                    (200/255,235/255,245/255),
                    (150/255,235/255,255/255),
                    (100/255,215/255,245/255),
                    (0      ,180/255,235/255),
                    (0      ,100/255,235/255),
                    (0      ,60/255 ,170/255),
                    (0      ,30/255 ,120/255)]
    return colors_diff

def set_difgrenzen():    
    grenzen_diff = [-2,-1,-0.5,-0.2,-0.1,-0.05, -0.03,0.03,0.05,0.1,0.2,0.5,1,2]
    return grenzen_diff


imod.visualize.plot_map(
        test, set_difcolors(), set_difgrenzen(), set_overlays(), figsize=(12, 12))
```
but ended up with empty triangles in the upper en lower legend

![afbeelding](https://github.com/Deltares/imod-python/assets/57228568/2a1a5230-6230-409a-86d6-495e68e121ab)

**Comment by JoerivanEngelen** [comment]
You can turn this behavior off by providing the following argument:

```python 
imod.visualize.plot_map(data, set_difcolors(), set_difgrenzen(), kwargs_colorbar = dict(whiten_triangles = False))
```

**Comment by JaccoHoogewoud** [comment]
thx! perhaps this could be the standerd setting?

**Comment by JoerivanEngelen** [comment]
By default whiten triangles is turned on, and it only whitens the triangles if no data falls outside the value range. I think it supposed to also mask the triangle edges, which is the best behavior I reckon (similar to what xarray does).

**Comment by JaccoHoogewoud** [comment]
I guessed something like that. But this way the legend changes (a little bit) if the data changes....

**Comment by JoerivanEngelen** [comment]
I looked a bit further into this and discussed with @Huite, [it turns out this behavior was the default already since the introduction of ``plot_map``](https://github.com/Deltares/imod-python/commit/4b83465c78984dc95ebef12134c338bf73115cb2)

The reason for this was that xarray tends to rescale the colorbar when data falls outside or inside the range, as in: when data falls outside the range, it adds the triangle. This causes the situation where, when data falls inside the range, the colorbar is stretched more than when it falls outside of the range (because of the addition of the triangles). This can make it quite hard to compare two colorbars of two figures, despite having the same boundaries set. 

Therefore, we decided to always add the triangle, to preserve colorbar scale. It is whitened when no data falls outside the range. Frankly, it is not an entirely ideal situation, as the triangle edge is not whitened, but I don't have a better suggestion which wouldn't require a lot of work, except changing default behavior. I defer from doing this for a function existing for 5 years, without very good reasons. 

Closing this for now, if this is hampering/blocking you a lot in work, please re-open.
