### ISSUE TITLE
mf6 GroundwaterFlowModel docstring doesn't mention arguments, only **kwargs

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-python#983]
Question from Ilja, regarding Newton option:

https://deltares.github.io/imod-python/api/generated/mf6/imod.mf6.GroundwaterFlowModel.html

This is currently unfindable? I had to check the source to figure it out.

**Comment by JoerivanEngelen** [comment]
This is likely because a docstring is missing for the ``GroundwaterFlowModlow`` object. I think we didn't add this from the start because at the start it didn't have any arguments, so docstring wasn't that exciting (though still useful to describe what the object does). 

Since we added all kinds of options to ``GroundwaterFlowModlow``, a docstring is a hard necessity.
